name: Electron Build
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        
    defaults:
      run:
        working-directory: ./src

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Wine and dependencies (Ubuntu only)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install wine32
        
    - name: Install dependencies
      run: |
        chmod -R 755 ../*
        npm install
           
    - name: electron-builder on MacOS
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        sudo target=darwin npx electron-builder build --mac --universal
    
    - name: Upload artifacts on MacOS
      if: ${{ matrix.os == 'macos-latest' }}
      uses: actions/upload-artifact@v4
      with:
        name: mac
        path: |
          ./src/build/*.dmg
        
    - name: electron-builder on Windows
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: target=win32 npx electron-builder --win
        
    - name: Upload artifacts on Windows
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: actions/upload-artifact@v4
      with:
        name: win
        path: |
          ./src/build/*.exe